#!/usr/bin/env bash
# ============================================================================
# aide.sh - AIDE 入侵检测模块
# 文件完整性检查系统，使用 aide (Advanced Intrusion Detection Environment)
# ============================================================================
set -eo pipefail
# 注意: 不使用 -u (nounset)，与 utils.sh 保持一致，避免未绑定变量导致脚本意外退出

# Source guard: prevent double-source crash under set -eo pipefail
[[ -n "${_AIDE_LOADED:-}" ]] && return 0
readonly _AIDE_LOADED=1

# 检查依赖
if [[ "${_UTILS_LOADED:-}" != "1" ]]; then
    echo "Error: utils.sh must be loaded before aide.sh"
    exit 1
fi

# ============================================================================
# 配置常量
# ============================================================================

AIDE_CONF="/etc/aide/aide.conf"
AIDE_DB_DIR="/var/lib/aide"
AIDE_DB="${AIDE_DB_DIR}/aide.db.gz"
AIDE_DB_NEW="${AIDE_DB_DIR}/aide.db.new.gz"
AIDE_CRON_FILE="/etc/cron.d/aide-check"
AIDE_REPORT_DIR="/var/log/aide"

# 动态解析 aide 二进制路径
AIDE_BIN=$(command -v aide 2>/dev/null || echo "/usr/sbin/aide")
readonly AIDE_BIN

# ============================================================================
# 内部函数
# ============================================================================

# 安装 AIDE（跨发行版）
_install_aide() {
    if command_exists aide; then
        log_info "${MSG_AIDE_ALREADY_INSTALLED}"
        return 0
    fi

    log_step "${MSG_AIDE_INSTALL}"

    case "${DETECTED_OS:-}" in
        ubuntu|debian)
            apt-get install -y aide >> "${LOG_FILE}" 2>&1 || {
                log_error "${MSG_AIDE_INSTALL} failed"
                return 1
            }
            ;;
        centos|rhel|rocky|almalinux)
            # EPEL for RHEL-family
            if ! command_exists aide; then
                yum install -y epel-release >> "${LOG_FILE}" 2>&1 || true
                yum install -y aide >> "${LOG_FILE}" 2>&1 || {
                    log_error "${MSG_AIDE_INSTALL} failed"
                    return 1
                }
            fi
            ;;
        fedora)
            dnf install -y aide >> "${LOG_FILE}" 2>&1 || {
                log_error "${MSG_AIDE_INSTALL} failed"
                return 1
            }
            ;;
        *)
            log_error "${MSG_AIDE_UNSUPPORTED_OS}"
            return 1
            ;;
    esac

    log_success "${MSG_AIDE_INSTALL_DONE}"
}

# 备份现有的 aide.conf
_backup_aide_config() {
    if [[ -f "${AIDE_CONF}" ]]; then
        backup_file "${AIDE_CONF}"
    fi
}

# 生成最小 aide.conf 配置
_configure_aide() {
    log_step "${MSG_AIDE_CONFIGURE}"

    _backup_aide_config

    # 确保目录存在
    mkdir -p "${AIDE_DB_DIR}" "${AIDE_REPORT_DIR}"

    # 原子写入配置
    local tmp_conf date_stamp
    tmp_conf=$(mktemp)
    date_stamp=$(date +%Y%m%d)

    cat > "${tmp_conf}" <<EOF
# AIDE configuration - Generated by linux-one-key
# This file controls which files/directories are monitored

# Database location
database_in=file:${AIDE_DB_DIR}/aide.db.gz
database_new=file:${AIDE_DB_DIR}/aide.db.new.gz
gzip_dbout=yes
verbose=5
report_url=file:${AIDE_REPORT_DIR}/aide-report-${date_stamp}.txt

# Rule definitions
# p: permissions, i: inode, n: number of links, u: user, g: group
# s: size, b: block count, m: mtime, a: atime, c: ctime
# S: check sha1, R: check rmd160, sha256, sha512, tiger
# >: growing log file (check size+perms only)

# Standard rules
ALL = p+i+n+u+g+s+b+m+c+sha512+sha256+sha1+rmd160+tiger
NORMAL = p+i+n+u+g+s+b+m+c+sha512
DIR = p+i+n+u+g
PERMS = p+i+u+g
LOG = p+i+n+u+g+s+b+sha512
LSPP = p+i+n+u+g+s+b+m+c+sha512

# Critical system files
/etc/passwd ALL
/etc/shadow ALL
/etc/group ALL
/etc/gshadow ALL
/etc/sudoers ALL
/etc/ssh/sshd_config ALL
/etc/hosts ALL
/etc/crontab ALL
/etc/hostname PERMS

# System directories
/sbin ALL
/bin ALL
/usr/sbin ALL
/usr/bin ALL
/lib ALL
/lib64 ALL
/usr/lib ALL
/usr/lib64 ALL

# Root home directory
/root ALL

# Boot directory
/boot ALL

# /etc directory (recursive, exclude some)
/etc NORMAL
!/etc/aide.conf
!/etc/mtab
!/etc/fstab
!/etc/mdns

# Log files (growing, size+perms only)
/var/log LOG
!/var/log/aide

# Skip temporary/volatile directories
!/proc
!/sys
!/dev
!/run
!/mnt
!/media
!/var/tmp
!/tmp
!/var/cache
EOF

    mv "${tmp_conf}" "${AIDE_CONF}"
    log_success "${MSG_AIDE_CONFIGURE_DONE}"
}

# 初始化 AIDE 数据库
_init_aide_database() {
    log_step "${MSG_AIDE_INIT_DB}"

    # 检查数据库是否已存在
    if [[ -f "${AIDE_DB}" ]]; then
        log_info "${MSG_AIDE_INIT_DB_EXISTS}"
        if confirm "${MSG_AIDE_INIT_DB_REINIT}" "n"; then
            rm -f "${AIDE_DB}" "${AIDE_DB_NEW}"
        else
            log_info "${MSG_AIDE_INIT_DB_SKIP}"
            return 0
        fi
    fi

    # 提示用户初始化可能耗时
    log_warn "${MSG_AIDE_INIT_DB_WARN}"

    # 检测 aideinit 二进制名（跨发行版）
    if command_exists aideinit; then
        aideinit --init >> "${LOG_FILE}" 2>&1 || {
            log_error "${MSG_AIDE_INIT_DB} failed"
            return 1
        }
    elif command_exists aide; then
        aide --init >> "${LOG_FILE}" 2>&1 || {
            log_error "${MSG_AIDE_INIT_DB} failed"
            return 1
        }
    else
        log_error "${MSG_AIDE_INSTALL} not found"
        return 1
    fi

    # 将 .new 数据库移动到正式位置
    if [[ -f "${AIDE_DB_NEW}" ]]; then
        mv "${AIDE_DB_NEW}" "${AIDE_DB}"
    else
        log_error "${MSG_AIDE_INIT_DB} database file not created"
        return 1
    fi

    log_success "${MSG_AIDE_INIT_DB_DONE}"
}

# 设置每日检查 cron
_setup_aide_cron() {
    log_step "${MSG_AIDE_CRON_SETUP}"

    # 检查 cron 是否已存在
    if [[ -f "${AIDE_CRON_FILE}" ]]; then
        log_info "${MSG_AIDE_CRON_EXISTS}"
        return 0
    fi

    # 确保 cron 服务在运行
    if command_exists systemctl; then
        if ! systemctl is-active --quiet cron 2>/dev/null && ! systemctl is-active --quiet crond 2>/dev/null; then
            log_warn "cron service not running, aide cron may not execute"
        fi
    fi

    # 创建 cron 文件
    mkdir -p "$(dirname "${AIDE_CRON_FILE}")"

    cat > "${AIDE_CRON_FILE}" <<EOF
# AIDE daily check - Generated by linux-one-key
# Runs daily at 02:00, checks file integrity
0 2 * * * root ${AIDE_BIN} --check > ${AIDE_REPORT_DIR}/check-\$(date +\%Y\%m\%d).log 2>&1
EOF

    chmod 644 "${AIDE_CRON_FILE}"
    log_success "${MSG_AIDE_CRON_DONE}"
}

# 显示 AIDE 状态信息
_show_aide_status() {
    echo ""
    echo -e "${BOLD}${MSG_AIDE_STATUS}${NC}"
    echo ""

    if ! command_exists aide; then
        echo -e "  ${YELLOW}${MSG_AIDE_NOT_INSTALLED}${NC}"
        echo ""
        return 0
    fi

    echo -e "  ${MSG_AIDE_DB_STATUS}:"
    if [[ -f "${AIDE_DB}" ]]; then
        local db_time db_age
        db_time=$(stat -c %Y "${AIDE_DB}" 2>/dev/null || stat -f %m "${AIDE_DB}" 2>/dev/null || echo "0")
        db_age=$(( $(date +%s) - db_time ))
        local db_age_days=$(( db_age / 86400 ))
        echo -e "    ${GREEN}✅${NC} ${MSG_AIDE_DB_AGE}: ${db_age_days} ${MSG_TIME_DAYS_AGO}"
    else
        echo -e "    ${YELLOW}⚠️${NC} ${MSG_AIDE_DB_STATUS}: N/A"
    fi

    echo -e "  ${MSG_AIDE_CRON_FILE}:"
    if [[ -f "${AIDE_CRON_FILE}" ]]; then
        echo -e "    ${GREEN}✅${NC} ${MSG_AIDE_CRON_DONE}"
    else
        echo -e "    ${YELLOW}⚠️${NC} ${MSG_AIDE_CRON_SKIP}"
    fi
    echo ""
}

# 显示 AIDE 管理提示
_show_aide_tips() {
    echo ""
    echo -e "${BOLD}${MSG_AIDE_TIPS_TITLE}${NC}"
    echo ""
    echo -e "  ${MSG_AIDE_TIPS_1}"
    echo -e "  ${MSG_AIDE_TIPS_2}"
    echo -e "  ${MSG_AIDE_TIPS_3}"
    echo -e "  ${MSG_AIDE_TIPS_4}"
    echo ""
}

# ============================================================================
# 公共接口函数
# ============================================================================

# 运行 AIDE 完整配置向导
run_aide_wizard() {
    log_title "${MSG_AIDE_WIZARD_TITLE}"

    # Check root
    if ! is_root; then
        log_error "${MSG_ERROR_NOT_ROOT}"
        return 1
    fi

    echo ""
    echo -e "${BOLD}${MSG_AIDE_WIZARD_DESC}${NC}"
    echo ""

    if ! confirm "${MSG_AIDE_WIZARD_START}" "y"; then
        log_info "${MSG_AIDE_WIZARD_SKIPPED}"
        return 0
    fi

    local wizard_rc=0

    # ── Step 1: Install ──
    _install_aide || wizard_rc=1

    # ── Step 2: Configure ──
    if [[ ${wizard_rc} -eq 0 ]]; then
        _configure_aide || wizard_rc=1
    fi

    # ── Step 3: Init Database ──
    if [[ ${wizard_rc} -eq 0 ]]; then
        _init_aide_database || wizard_rc=1
    fi

    # ── Step 4: Setup Cron ──
    if [[ ${wizard_rc} -eq 0 ]]; then
        if confirm "${MSG_AIDE_CRON_SETUP}?" "y"; then
            _setup_aide_cron || wizard_rc=1
        else
            log_info "${MSG_AIDE_CRON_SKIP}"
        fi
    fi

    # ── Summary ──
    echo ""
    log_title "${MSG_AIDE_SUMMARY}"

    _show_aide_status

    if [[ ${wizard_rc} -eq 0 ]]; then
        log_success "${MSG_AIDE_WIZARD_DONE}"
    else
        log_warn "${MSG_AIDE_WIZARD_DONE} ${MSG_WIZARD_ERR_HINT}"
    fi

    _show_aide_tips

    return ${wizard_rc}
}

# 检查 AIDE 状态（用于系统状态检测）
# 输出: key=value 格式
check_aide_status() {
    local db_exists="no"
    local cron_enabled="no"

    if [[ -f "${AIDE_DB}" ]]; then
        db_exists="yes"
    fi

    if [[ -f "${AIDE_CRON_FILE}" ]]; then
        cron_enabled="yes"
    fi

    echo "aide_db_exists=${db_exists}"
    echo "aide_cron=${cron_enabled}"
}

log_debug "aide.sh loaded successfully"
