#!/usr/bin/env bash
# ============================================================================
# clamav.sh - ClamAV 病毒扫描模块
# 开源杀毒软件，使用 freshclam + 按需扫描（不使用 clamd 守护进程）
# ============================================================================
set -eo pipefail
# 注意: 不使用 -u (nounset)，与 utils.sh 保持一致，避免未绑定变量导致脚本意外退出

# Source guard: prevent double-source crash under set -eo pipefail
[[ -n "${_CLAMAV_LOADED:-}" ]] && return 0
readonly _CLAMAV_LOADED=1

# 检查依赖
if [[ "${_UTILS_LOADED:-}" != "1" ]]; then
    echo "Error: utils.sh must be loaded before clamav.sh"
    exit 1
fi

# ============================================================================
# 配置常量
# ============================================================================

CLAMAV_CONF_DIR="/etc/clamav"
# shellcheck disable=SC2034 # reserved for clamd (not enabled by default)
CLAMAVD_CONF="${CLAMAV_CONF_DIR}/clamd.conf"
FRESHCLAM_CONF="${CLAMAV_CONF_DIR}/freshclam.conf"
CLAMAV_LOG_DIR="/var/log/clamav"
CLAMAV_QUARANTINE_DIR="/var/quarantine"
CLAMAV_CRON_UPDATE="/etc/cron.d/clamav-freshclam"
CLAMAV_CRON_SCAN="/etc/cron.d/clamav-scan"

# ============================================================================
# 内部函数
# ============================================================================

# 安装 ClamAV（跨发行版）
_install_clamav() {
    if command_exists clamscan; then
        log_info "${MSG_CLAMAV_ALREADY_INSTALLED}"
        return 0
    fi

    log_step "${MSG_CLAMAV_INSTALL}"

    case "${DETECTED_OS:-}" in
        ubuntu|debian)
            apt-get install -y clamav clamav-daemon >> "${LOG_FILE}" 2>&1 || {
                log_error "${MSG_CLAMAV_INSTALL} failed"
                return 1
            }
            # Stop clamd if auto-started (we only want freshclam + on-demand)
            if command -v systemctl &>/dev/null; then
                systemctl stop clamav-daemon >> "${LOG_FILE}" 2>&1 || true
                systemctl disable clamav-daemon >> "${LOG_FILE}" 2>&1 || true
                # Also stop freshclam systemd service to prevent conflicts with cron
                systemctl stop clamav-freshclam >> "${LOG_FILE}" 2>&1 || true
                systemctl disable clamav-freshclam >> "${LOG_FILE}" 2>&1 || true
                systemctl mask clamav-freshclam >> "${LOG_FILE}" 2>&1 || true
                systemctl stop clamav-freshclam.timer >> "${LOG_FILE}" 2>&1 || true
                systemctl disable clamav-freshclam.timer >> "${LOG_FILE}" 2>&1 || true
            fi
            ;;
        centos|rhel|rocky|almalinux)
            # EPEL for RHEL-family
            yum install -y epel-release >> "${LOG_FILE}" 2>&1 || true
            yum install -y clamav clamav-update >> "${LOG_FILE}" 2>&1 || {
                log_error "${MSG_CLAMAV_INSTALL} failed"
                return 1
            }
            ;;
        fedora)
            dnf install -y epel-release >> "${LOG_FILE}" 2>&1 || true
            dnf install -y clamav clamav-update >> "${LOG_FILE}" 2>&1 || {
                log_error "${MSG_CLAMAV_INSTALL} failed"
                return 1
            }
            ;;
        *)
            log_error "${MSG_CLAMAV_UNSUPPORTED_OS}"
            return 1
            ;;
    esac

    log_success "${MSG_CLAMAV_INSTALL_DONE}"
}

# 生成最小 freshclam.conf 配置
_configure_freshclam() {
    log_step "${MSG_CLAMAV_CONFIGURE}"

    # 确保目录存在
    mkdir -p "${CLAMAV_CONF_DIR}" "${CLAMAV_LOG_DIR}"

    # 备份已有配置
    if [[ -f "${FRESHCLAM_CONF}" ]]; then
        backup_file "${FRESHCLAM_CONF}"
    fi

    local tmp_conf
    tmp_conf=$(mktemp)

    cat > "${tmp_conf}" <<EOF
# freshclam.conf - Generated by linux-one-key
# Virus database update configuration

# Database directory
DatabaseDirectory ${CLAMAV_LOG_DIR}

# Update URL
DatabaseMirror db.local.clamav.net
DatabaseMirror database.clamav.net

# Logging
UpdateLogFile ${CLAMAV_LOG_DIR}/freshclam.log
LogTime yes
LogVerbose no

# Checks
Checks 24
NotifyClamd /etc/clamav/clamd.conf

# Safe mode
SafeBrowsing yes
Bytecode yes
CompressLocalDatabase yes
EOF

    mv "${tmp_conf}" "${FRESHCLAM_CONF}"

    log_success "${MSG_CLAMAV_CONFIGURE_DONE}"
}

# 设置 hourly freshclam cron
_setup_freshclam_cron() {
    log_step "${MSG_CLAMAV_FRESHCLAM_CRON}"

    if [[ -f "${CLAMAV_CRON_UPDATE}" ]]; then
        log_info "${MSG_CLAMAV_FRESHCLAM_CRON_DONE} (already exists)"
        return 0
    fi

    mkdir -p "$(dirname "${CLAMAV_CRON_UPDATE}")"

    cat > "${CLAMAV_CRON_UPDATE}" <<'EOF'
# ClamAV freshclam hourly update - Generated by linux-one-key
# Runs every 6 hours to update virus definitions
0 */6 * * * root /usr/bin/freshclam --quiet > /dev/null 2>&1
EOF

    chmod 644 "${CLAMAV_CRON_UPDATE}"
    log_success "${MSG_CLAMAV_FRESHCLAM_CRON_DONE}"
}

# 立即运行 freshclam 更新病毒库
_run_freshclam_now() {
    log_step "${MSG_CLAMAV_FRESHCLAM_NOW}"

    log_warn "${MSG_CLAMAV_FRESHCLAM_NOW_WARN}"

    if freshclam --stdout >> "${LOG_FILE}" 2>&1; then
        log_success "${MSG_CLAMAV_FRESHCLAM_NOW_DONE}"
    else
        log_warn "${MSG_CLAMAV_FRESHCLAM_NOW_WARN}"
        return 1
    fi
}

# 设置每日扫描 cron（可选）
_setup_scan_cron() {
    log_step "${MSG_CLAMAV_SCAN_CRON_SETUP}"

    if [[ -f "${CLAMAV_CRON_SCAN}" ]]; then
        log_info "${MSG_CLAMAV_SCAN_CRON_DONE} (already exists)"
        return 0
    fi

    mkdir -p "$(dirname "${CLAMAV_CRON_SCAN}")"

    # Daily scan at 03:00, excluding /proc and /sys
    cat > "${CLAMAV_CRON_SCAN}" <<'EOF'
# ClamAV daily scan - Generated by linux-one-key
# Runs daily at 03:00, scans /home /tmp /var
0 3 * * * root /usr/bin/nice -n 19 /usr/bin/ionice -c3 /usr/bin/clamscan --quiet -r /home /tmp /var --exclude-dir='^/proc' --exclude-dir='^/sys' --move=/var/quarantine -l /var/log/clamav/scan-$(date +\%Y\%m\%d).log > /dev/null 2>&1
EOF

    chmod 644 "${CLAMAV_CRON_SCAN}"
    log_success "${MSG_CLAMAV_SCAN_CRON_DONE}"
}

# 执行按需扫描
_run_clamav_scan() {
    log_step "${MSG_CLAMAV_RUN_SCAN}"

    mkdir -p "${CLAMAV_QUARANTINE_DIR}"
    mkdir -p "${CLAMAV_LOG_DIR}"

    local scan_log
    scan_log="${CLAMAV_LOG_DIR}/scan-ondemand-$(date +%Y%m%d-%H%M%S).log"
    local threats_found=0

    if nice -n 19 ionice -c3 clamscan --quiet -r /home /tmp /var \
        --exclude-dir='^/proc' --exclude-dir='^/sys' \
        --move="${CLAMAV_QUARANTINE_DIR}" \
        -l "${scan_log}" >> "${LOG_FILE}" 2>&1; then
        threats_found=0
    else
        # ClamAV returns 1 when viruses are found
        threats_found=1
    fi

    if [[ "${threats_found}" -eq 0 ]]; then
        log_success "${MSG_CLAMAV_SCAN_CLEAN}"
    else
        log_warn "${MSG_CLAMAV_SCAN_FOUND}"
        log_info "${MSG_CLAMAV_LAST_SCAN}: ${scan_log}"
    fi
}

# 显示 ClamAV 状态
_show_clamav_status() {
    echo ""
    echo -e "${BOLD}${MSG_CLAMAV_STATUS}${NC}"
    echo ""

    if ! command_exists clamscan; then
        echo -e "  ${YELLOW}${MSG_CLAMAV_NOT_INSTALLED}${NC}"
        echo ""
        return 0
    fi

    # Check DB status
    echo -e "  ${MSG_CLAMAV_DB_STATUS}:"
    if [[ -f "${CLAMAV_LOG_DIR}/daily.cld" ]] || [[ -f "${CLAMAV_LOG_DIR}/daily.cvd" ]]; then
        local db_time db_age
        if [[ -f "${CLAMAV_LOG_DIR}/daily.cld" ]]; then
            db_time=$(stat -c %Y "${CLAMAV_LOG_DIR}/daily.cld" 2>/dev/null || stat -f %m "${CLAMAV_LOG_DIR}/daily.cld" 2>/dev/null || echo "0")
        else
            db_time=$(stat -c %Y "${CLAMAV_LOG_DIR}/daily.cvd" 2>/dev/null || stat -f %m "${CLAMAV_LOG_DIR}/daily.cvd" 2>/dev/null || echo "0")
        fi
        db_age=$(( $(date +%s) - db_time ))
        local db_age_days=$(( db_age / 86400 ))
        if [[ "${db_age_days}" -le 7 ]]; then
            echo -e "    ${GREEN}✅${NC} ${MSG_CLAMAV_DB_UPTODATE} (${db_age_days} ${MSG_TIME_DAYS_AGO#%d })"
        else
            echo -e "    ${YELLOW}⚠️${NC} ${MSG_CLAMAV_DB_OUTDATED} (${db_age_days} ${MSG_TIME_DAYS_AGO#%d })"
        fi
    else
        echo -e "    ${YELLOW}⚠️${NC} ${MSG_CLAMAV_NOT_INSTALLED} (run freshclam first)"
    fi

    # Check cron status
    echo -e "  ${MSG_CLAMAV_STATUS}:"
    if [[ -f "${CLAMAV_CRON_UPDATE}" ]]; then
        echo -e "    ${GREEN}✅${NC} ${MSG_CLAMAV_FRESHCLAM_CRON_DONE}"
    else
        echo -e "    ${YELLOW}⚠️${NC} ${MSG_CLAMAV_SCAN_CRON_SKIP}"
    fi
    echo ""
}

# 显示 ClamAV 管理提示
_show_clamav_tips() {
    echo ""
    echo -e "${BOLD}${MSG_CLAMAV_TIPS_TITLE}${NC}"
    echo ""
    echo -e "  ${MSG_CLAMAV_TIPS_1}"
    echo -e "  ${MSG_CLAMAV_TIPS_2}"
    echo -e "  ${MSG_CLAMAV_TIPS_3}"
    echo -e "  ${MSG_CLAMAV_TIPS_4}"
    echo ""
}

# ============================================================================
# 公共接口函数
# ============================================================================

# 运行 ClamAV 完整配置向导
run_clamav_wizard() {
    log_title "${MSG_CLAMAV_WIZARD_TITLE}"

    # Check root
    if ! is_root; then
        log_error "${MSG_ERROR_NOT_ROOT}"
        return 1
    fi

    echo ""
    echo -e "${BOLD}${MSG_CLAMAV_WIZARD_DESC}${NC}"
    echo ""

    # Memory warning
    log_warn "${MSG_CLAMAV_MEMORY_WARN}"
    if ! confirm "${MSG_CLAMAV_MEMORY_CONFIRM}" "y"; then
        log_info "${MSG_CLAMAV_WIZARD_SKIPPED}"
        return 0
    fi

    if ! confirm "${MSG_CLAMAV_WIZARD_START}" "y"; then
        log_info "${MSG_CLAMAV_WIZARD_SKIPPED}"
        return 0
    fi

    local wizard_rc=0

    # ── Step 1: Install ──
    _install_clamav || wizard_rc=1

    # ── Step 2: Configure freshclam ──
    if [[ ${wizard_rc} -eq 0 ]]; then
        _configure_freshclam || wizard_rc=1
    fi

    # ── Step 3: Setup freshclam cron ──
    if [[ ${wizard_rc} -eq 0 ]]; then
        _setup_freshclam_cron || wizard_rc=1
    fi

    # ── Step 4: Run freshclam now ──
    if [[ ${wizard_rc} -eq 0 ]]; then
        if confirm "${MSG_CLAMAV_FRESHCLAM_CRON}?" "y"; then
            _run_freshclam_now || wizard_rc=1
        fi
    fi

    # ── Step 5: Optional scan cron ──
    if [[ ${wizard_rc} -eq 0 ]]; then
        if confirm "${MSG_CLAMAV_SCAN_CRON_PROMPT}" "n"; then
            _setup_scan_cron || true
        fi
    fi

    # ── Summary ──
    echo ""
    log_title "${MSG_CLAMAV_SUMMARY}"

    _show_clamav_status

    if [[ ${wizard_rc} -eq 0 ]]; then
        log_success "${MSG_CLAMAV_WIZARD_DONE}"
    else
        log_warn "${MSG_CLAMAV_WIZARD_DONE} ${MSG_WIZARD_ERR_HINT}"
    fi

    _show_clamav_tips

    return ${wizard_rc}
}

# 检查 ClamAV 状态（用于系统状态检测）
# 输出: key=value 格式
check_clamav_status() {
    local db_uptodate="no"
    local cron_enabled="no"

    # Check DB status
    if [[ -f "${CLAMAV_LOG_DIR}/daily.cld" ]] || [[ -f "${CLAMAV_LOG_DIR}/daily.cvd" ]]; then
        local db_file
        if [[ -f "${CLAMAV_LOG_DIR}/daily.cld" ]]; then
            db_file="${CLAMAV_LOG_DIR}/daily.cld"
        else
            db_file="${CLAMAV_LOG_DIR}/daily.cvd"
        fi
        local db_time db_age
        db_time=$(stat -c %Y "${db_file}" 2>/dev/null || stat -f %m "${db_file}" 2>/dev/null || echo "0")
        db_age=$(( $(date +%s) - db_time ))
        local db_age_days=$(( db_age / 86400 ))
        if [[ "${db_age_days}" -le 7 ]]; then
            db_uptodate="yes"
        fi
    fi

    if [[ -f "${CLAMAV_CRON_UPDATE}" ]]; then
        cron_enabled="yes"
    fi

    echo "clamav_db_uptodate=${db_uptodate}"
    echo "clamav_cron_enabled=${cron_enabled}"
}

log_debug "clamav.sh loaded successfully"
