#!/usr/bin/env bash
# ============================================================================
# rootkit.sh - Rootkit 检测模块
# 使用 rkhunter + chkrootkit 检测系统是否被植入后门
# ============================================================================
set -eo pipefail
# 注意: 不使用 -u (nounset)，与 utils.sh 保持一致，避免未绑定变量导致脚本意外退出

# Source guard: prevent double-source crash under set -eo pipefail
[[ -n "${_ROOTKIT_LOADED:-}" ]] && return 0
readonly _ROOTKIT_LOADED=1

# 检查依赖
if [[ "${_UTILS_LOADED:-}" != "1" ]]; then
    echo "Error: utils.sh must be loaded before rootkit.sh"
    exit 1
fi

# ============================================================================
# 配置常量
# ============================================================================

RKHUNTER_CONF="/etc/rkhunter.conf"
RKHUNTER_LOG_DIR="/var/log/rkhunter"
RKHUNTER_CRON="/etc/cron.d/rkhunter"
CHKROOTKIT_LOG_DIR="/var/log/chkrootkit"
# shellcheck disable=SC2034 # used by rkhunter internally, kept for reference
RKHUNTER_PROP_FILE="/var/lib/rkhunter/db/rkhunter.dat"

# ============================================================================
# 内部函数
# ============================================================================

# 安装 rkhunter（跨发行版）
_install_rkhunter() {
    if command_exists rkhunter; then
        log_info "${MSG_ROOTKIT_RKHUNTER_ALREADY}"
        return 0
    fi

    log_step "${MSG_ROOTKIT_INSTALL_RKHUNTER}"

    case "${DETECTED_OS:-}" in
        ubuntu|debian)
            apt-get install -y rkhunter >> "${LOG_FILE}" 2>&1 || {
                log_error "rkhunter installation failed"
                return 1
            }
            ;;
        centos|rhel|rocky|almalinux)
            # EPEL for RHEL-family
            yum install -y epel-release >> "${LOG_FILE}" 2>&1 || true
            yum install -y rkhunter >> "${LOG_FILE}" 2>&1 || {
                log_error "rkhunter installation failed"
                return 1
            }
            ;;
        fedora)
            dnf install -y epel-release >> "${LOG_FILE}" 2>&1 || true
            dnf install -y rkhunter >> "${LOG_FILE}" 2>&1 || {
                log_error "rkhunter installation failed"
                return 1
            }
            ;;
        *)
            log_error "${MSG_ROOTKIT_UNSUPPORTED_OS}"
            return 1
            ;;
    esac

    log_success "${MSG_ROOTKIT_INSTALL_RKHUNTER_DONE}"
}

# 安装 chkrootkit（仅 apt 可用，RHEL 系优雅跳过）
_install_chkrootkit() {
    if command_exists chkrootkit; then
        log_info "${MSG_ROOTKIT_CHKROOTKIT_ALREADY}"
        return 0
    fi

    log_step "${MSG_ROOTKIT_INSTALL_CHKROOTKIT}"

    case "${DETECTED_OS:-}" in
        ubuntu|debian)
            apt-get install -y chkrootkit >> "${LOG_FILE}" 2>&1 || {
                log_warn "chkrootkit installation failed, continuing without it"
                return 1
            }
            log_success "${MSG_ROOTKIT_INSTALL_CHKROOTKIT_DONE}"
            ;;
        centos|rhel|rocky|almalinux|fedora)
            log_warn "${MSG_ROOTKIT_CHKROOTKIT_UNAVAIL}"
            return 1
            ;;
        *)
            log_warn "${MSG_ROOTKIT_CHKROOTKIT_UNAVAIL}"
            return 1
            ;;
    esac

    return 0
}

# 配置 rkhunter
_configure_rkhunter() {
    log_step "${MSG_ROOTKIT_CONFIGURE}"

    # 确保目录存在
    mkdir -p "${RKHUNTER_LOG_DIR}" "${CHKROOTKIT_LOG_DIR}"

    # 备份已有配置
    if [[ -f "${RKHUNTER_CONF}" ]]; then
        backup_file "${RKHUNTER_CONF}"
    fi

    local tmp_conf
    tmp_conf=$(mktemp)

    cat > "${tmp_conf}" <<'EOF'
# rkhunter.conf - Generated by linux-one-key
# Rootkit Hunter configuration

# Email reporting
MAILTO=root
MAILON=WARNING

# Report method
REPORT_METHOD=stdout

# Database directory
TMPDIR=/tmp

# Logging
LOGFILE=/var/log/rkhunter/rkhunter.log
APPEND_LOG=1

# Update mirror
UPDATE_MIRROR=rkhunter.sourceforge.net
MIRRORS_MODE=1

# Check settings
ENABLE_TESTS=all
DISABLE_TESTS=suspscan
ALLOW_SSH_ROOT_USER=yes
ALLOW_SSH_PROT_V1=0
ALLOW_SYSLOG_REMOTE_LOGGING=0

# Script whitelist
SCRIPTWHITELIST_DIR=/bin
SCRIPTWHITELIST_DIR=/usr/bin
SCRIPTWHITELIST_DIR=/sbin
SCRIPTWHITELIST_DIR=/usr/sbin

# Allow potentially false positives
ALLOWDEVFILE=/dev/shm
PHP_ALLOW_WRITABLE_DIRS=/var/lib/php/session

# Color output
COLOR_SET=0
EOF

    mv "${tmp_conf}" "${RKHUNTER_CONF}"

    log_success "${MSG_ROOTKIT_CONFIGURE_DONE}"
}

# 更新 rkhunter 文件属性数据库
_update_rkhunter_props() {
    log_step "${MSG_ROOTKIT_PROPUPD}"

    if ! rkhunter --propupd >> "${LOG_FILE}" 2>&1; then
        log_warn "${MSG_ROOTKIT_PROPUPD} failed"
        return 1
    fi

    log_success "${MSG_ROOTKIT_PROPUPD_DONE}"
}

# 设置每周 rkhunter cron（周日 03:00）
_setup_rkhunter_cron() {
    log_step "${MSG_ROOTKIT_CRON_SETUP}"

    if [[ -f "${RKHUNTER_CRON}" ]]; then
        log_info "${MSG_ROOTKIT_CRON_EXISTS}"
        return 0
    fi

    mkdir -p "$(dirname "${RKHUNTER_CRON}")"

    cat > "${RKHUNTER_CRON}" <<'EOF'
# rkhunter weekly scan - Generated by linux-one-key
# Runs every Sunday at 03:00
0 3 * * 0 root /usr/bin/rkhunter --check --skip-keypress --report-warnings-only --quiet 2>&1 | mail -s "rkhunter Weekly Report" root@localhost
EOF

    chmod 644 "${RKHUNTER_CRON}"
    log_success "${MSG_ROOTKIT_CRON_DONE}"
}

# 立即运行 rkhunter 扫描
_run_rkhunter_scan() {
    log_step "${MSG_ROOTKIT_RUN_SCAN}"

    log_warn "${MSG_ROOTKIT_SCAN_RUNNING}"

    if rkhunter --check --skip-keypress --report-warnings-only >> "${LOG_FILE}" 2>&1; then
        log_success "${MSG_ROOTKIT_SCAN_CLEAN}"
    else
        log_warn "${MSG_ROOTKIT_SCAN_FOUND}"
        log_info "${MSG_ROOTKIT_LAST_SCAN}: /var/log/rkhunter/rkhunter.log"
    fi
}

# 立即运行 chkrootkit 扫描
_run_chkrootkit_scan() {
    if ! command_exists chkrootkit; then
        log_info "${MSG_ROOTKIT_CHKROOTKIT_UNAVAIL}"
        return 0
    fi

    log_step "${MSG_ROOTKIT_INSTALL_CHKROOTKIT}"

    if chkrootkit >> "${CHKROOTKIT_LOG_DIR}/chkrootkit-$(date +%Y%m%d).log" 2>&1; then
        log_success "${MSG_ROOTKIT_SCAN_CLEAN}"
    else
        log_warn "${MSG_ROOTKIT_SCAN_FOUND}"
    fi
}

# 显示 rootkit 检测状态
_show_rootkit_status() {
    echo ""
    echo -e "${BOLD}${MSG_ROOTKIT_STATUS}${NC}"
    echo ""

    echo -e "  ${MSG_ROOTKIT_STATUS}:"
    if command_exists rkhunter; then
        echo -e "    ${GREEN}✅${NC} rkhunter: ${MSG_STATUS_INSTALLED}"
    else
        echo -e "    ${YELLOW}⚠️${NC} rkhunter: ${MSG_ROOTKIT_NOT_INSTALLED}"
    fi

    if command_exists chkrootkit; then
        echo -e "    ${GREEN}✅${NC} chkrootkit: ${MSG_STATUS_INSTALLED}"
    else
        echo -e "    ${YELLOW}⚠️${NC} chkrootkit: ${MSG_ROOTKIT_NOT_INSTALLED}"
    fi

    echo -e "  ${MSG_ROOTKIT_CRON_SETUP}:"
    if [[ -f "${RKHUNTER_CRON}" ]]; then
        echo -e "    ${GREEN}✅${NC} ${MSG_ROOTKIT_CRON_DONE}"
    else
        echo -e "    ${YELLOW}⚠️${NC} ${MSG_ROOTKIT_CRON_SKIP}"
    fi
    echo ""
}

# 显示 rootkit 检测管理提示
_show_rootkit_tips() {
    echo ""
    echo -e "${BOLD}${MSG_ROOTKIT_TIPS_TITLE}${NC}"
    echo ""
    echo -e "  ${MSG_ROOTKIT_TIPS_1}"
    echo -e "  ${MSG_ROOTKIT_TIPS_2}"
    echo -e "  ${MSG_ROOTKIT_TIPS_3}"
    echo -e "  ${MSG_ROOTKIT_TIPS_4}"
    echo ""
}

# ============================================================================
# 公共接口函数
# ============================================================================

# 运行 Rootkit 检测完整配置向导
run_rootkit_wizard() {
    log_title "${MSG_ROOTKIT_WIZARD_TITLE}"

    # Check root
    if ! is_root; then
        log_error "${MSG_ERROR_NOT_ROOT}"
        return 1
    fi

    echo ""
    echo -e "${BOLD}${MSG_ROOTKIT_WIZARD_DESC}${NC}"
    echo ""

    if ! confirm "${MSG_ROOTKIT_WIZARD_START}" "y"; then
        log_info "${MSG_ROOTKIT_WIZARD_SKIPPED}"
        return 0
    fi

    local wizard_rc=0

    # ── Step 1: Install rkhunter ──
    _install_rkhunter || wizard_rc=1

    # ── Step 2: Install chkrootkit ──
    if [[ ${wizard_rc} -eq 0 ]]; then
        _install_chkrootkit || true
    fi

    # ── Step 3: Configure rkhunter ──
    if [[ ${wizard_rc} -eq 0 ]]; then
        _configure_rkhunter || wizard_rc=1
    fi

    # ── Step 4: Update props ──
    if [[ ${wizard_rc} -eq 0 ]]; then
        _update_rkhunter_props || wizard_rc=1
    fi

    # ── Step 5: Run scan ──
    if [[ ${wizard_rc} -eq 0 ]]; then
        if confirm "${MSG_ROOTKIT_RUN_SCAN}?" "y"; then
            _run_rkhunter_scan || wizard_rc=1
        fi
    fi

    # ── Step 6: Run chkrootkit scan ──
    if [[ ${wizard_rc} -eq 0 ]]; then
        if command_exists chkrootkit; then
            if confirm "${MSG_ROOTKIT_INSTALL_CHKROOTKIT}?" "n"; then
                _run_chkrootkit_scan || true
            fi
        fi
    fi

    # ── Step 7: Setup cron ──
    if [[ ${wizard_rc} -eq 0 ]]; then
        if confirm "${MSG_ROOTKIT_CRON_SETUP}?" "y"; then
            _setup_rkhunter_cron || wizard_rc=1
        else
            log_info "${MSG_ROOTKIT_CRON_SKIP}"
        fi
    fi

    # ── Summary ──
    echo ""
    log_title "${MSG_ROOTKIT_SUMMARY}"

    _show_rootkit_status

    if [[ ${wizard_rc} -eq 0 ]]; then
        log_success "${MSG_ROOTKIT_WIZARD_DONE}"
    else
        log_warn "${MSG_ROOTKIT_WIZARD_DONE} ${MSG_WIZARD_ERR_HINT}"
    fi

    _show_rootkit_tips

    return ${wizard_rc}
}

# 检查 Rootkit 检测状态（用于系统状态检测）
# 输出: key=value 格式
check_rootkit_status() {
    local rkhunter_installed="no"
    local chkrootkit_installed="no"
    local cron_enabled="no"

    if command_exists rkhunter; then
        rkhunter_installed="yes"
    fi

    if command_exists chkrootkit; then
        chkrootkit_installed="yes"
    fi

    if [[ -f "${RKHUNTER_CRON}" ]]; then
        cron_enabled="yes"
    fi

    echo "rkhunter_installed=${rkhunter_installed}"
    echo "chkrootkit_installed=${chkrootkit_installed}"
    echo "cron_enabled=${cron_enabled}"
}

log_debug "rootkit.sh loaded successfully"
