#!/usr/bin/env bash
# ============================================================================
# sudo.sh - sudo 安全加固模块
# sudoers 默认参数收紧、加固 drop-in 写入（visudo 校验）、sudo 命令全量日志
# ============================================================================
set -eo pipefail
# 注意: 不使用 -u (nounset)，与 utils.sh 保持一致，避免未绑定变量导致脚本意外退出

# 检查依赖
if [[ "${_UTILS_LOADED:-}" != "1" ]]; then
    echo "Error: utils.sh must be loaded before sudo.sh"
    exit 1
fi

# ============================================================================
# 配置常量（允许测试通过环境变量覆盖路径）
# ============================================================================

# sudoers 加固 drop-in（须 chmod 0440 + visudo 校验）
SUDOERS_DROPIN="${SUDOERS_DROPIN:-/etc/sudoers.d/99-linux-one-key-sudo}"
# 主 sudoers 与 drop-in 目录（用于 NOPASSWD 白名单检查）
SUDOERS_MAIN="${SUDOERS_MAIN:-/etc/sudoers}"
SUDOERS_DIR="${SUDOERS_DIR:-/etc/sudoers.d}"
# sudo 命令日志文件
SUDO_LOG_FILE="${SUDO_LOG_FILE:-/var/log/sudo.log}"
# sudo 日志轮转配置
SUDO_LOGROTATE_CONF="${SUDO_LOGROTATE_CONF:-/etc/logrotate.d/linux-one-key-sudo}"
# sudo 凭证缓存超时（分钟）
SUDOERS_TIMESTAMP_TIMEOUT="${SUDOERS_TIMESTAMP_TIMEOUT:-5}"

# ============================================================================
# 内部函数
# ============================================================================

# 生成 sudoers 加固 drop-in 内容
_sudoers_dropin_content() {
    cat << EOF
## linux-one-key sudo hardening
## Generated by linux-one-key (Batch 5b)
## 收紧 sudo 默认行为 + 开启 sudo 命令全量日志

# 要求登录 tty（禁止 cron / 脚本等非交互环境直接执行 sudo）
Defaults requiretty

# 固定 PATH，避免被环境变量污染
Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# 缩短 sudo 凭证缓存时间，降低越权窗口
Defaults timestamp_timeout=${SUDOERS_TIMESTAMP_TIMEOUT}

# 全量记录 sudo 命令到独立日志
Defaults logfile="${SUDO_LOG_FILE}"
EOF
}

# 检查 drop-in 是否已包含全部加固指令（幂等判断）
_sudoers_already_hardened() {
    [[ -f "${SUDOERS_DROPIN}" ]] || return 1
    grep -q '^Defaults[[:space:]]\+requiretty' "${SUDOERS_DROPIN}" 2>/dev/null || return 1
    grep -q '^Defaults[[:space:]]\+secure_path=' "${SUDOERS_DROPIN}" 2>/dev/null || return 1
    grep -q '^Defaults[[:space:]]\+timestamp_timeout=' "${SUDOERS_DROPIN}" 2>/dev/null || return 1
    grep -q '^Defaults[[:space:]]\+logfile=' "${SUDOERS_DROPIN}" 2>/dev/null || return 1
    return 0
}

# 校验失败时回滚：有备份则恢复备份，无备份则删除
_rollback_sudoers_dropin() {
    local dropin="$1"
    local backup_path="$2"
    if [[ -n "${backup_path}" ]] && [[ -f "${backup_path}" ]]; then
        # drop-in 是 0440 只读，先删除再恢复（否则 cp 无法覆盖只读文件）
        rm -f "${dropin}" 2>/dev/null || true
        restore_file "${backup_path}" "${dropin}" "${MSG_SUDO_RESTORE_DROPIN}" || true
    else
        rm -f "${dropin}"
    fi
}

# 写入 sudoers 加固 drop-in（写前备份、写后 visudo 校验、失败立即回滚）
_write_sudoers_dropin() {
    local dropin="${SUDOERS_DROPIN}"
    mkdir -p "$(dirname "${dropin}")" 2>/dev/null || true

    # 幂等：已包含全部加固指令则跳过
    if _sudoers_already_hardened; then
        log_info "${MSG_SUDO_ALREADY_HARDENED}"
        return 0
    fi

    # 写入安全护栏：拒绝符号链接/超界目标文件
    if ! assert_safe_config_target "${dropin}"; then
        return 1
    fi

    local backup_path=""
    if [[ -f "${dropin}" ]]; then
        backup_path=$(backup_file "${dropin}" "${MSG_SUDO_BACKUP_DROPIN}") || return 1
        # 若为上次加固生成的 0440 只读文件，先删除再写入（备份已保存）
        rm -f "${dropin}" 2>/dev/null || true
    fi

    if ! _sudoers_dropin_content > "${dropin}"; then
        log_error "${MSG_SUDO_DROPIN_WRITE_FAILED}"
        _rollback_sudoers_dropin "${dropin}" "${backup_path}"
        return 1
    fi
    chmod 0440 "${dropin}" 2>/dev/null || true

    # 先校验单文件语法，再校验整体 sudoers（含所有 drop-in）
    if ! visudo -c -f "${dropin}" >/dev/null 2>&1 || ! visudo -c >/dev/null 2>&1; then
        log_error "${MSG_SUDO_VISUDO_FAILED}"
        _rollback_sudoers_dropin "${dropin}" "${backup_path}"
        return 1
    fi

    log_success "${MSG_SUDO_DROPIN_DONE}"
    return 0
}

# 确认 sudo 日志文件存在且权限为 root:root 0640
_ensure_sudo_log_perms() {
    if [[ ! -e "${SUDO_LOG_FILE}" ]]; then
        mkdir -p "$(dirname "${SUDO_LOG_FILE}")" 2>/dev/null || true
        touch "${SUDO_LOG_FILE}" 2>/dev/null || true
    fi
    if [[ -e "${SUDO_LOG_FILE}" ]]; then
        chown root:root "${SUDO_LOG_FILE}" 2>/dev/null || true
        chmod 0640 "${SUDO_LOG_FILE}" 2>/dev/null || true
        log_success "${MSG_SUDO_LOG_PERMS_DONE}: ${SUDO_LOG_FILE}"
    fi
}

# 写入 sudo 日志轮转配置
_write_logrotate_dropin() {
    local conf="${SUDO_LOGROTATE_CONF}"
    if [[ -f "${conf}" ]] && grep -q 'linux-one-key sudo' "${conf}" 2>/dev/null; then
        log_info "${MSG_SUDO_LOGROTATE_EXISTS}"
        return 0
    fi
    mkdir -p "$(dirname "${conf}")" 2>/dev/null || true
    cat > "${conf}" << EOF
# linux-one-key sudo log rotation
${SUDO_LOG_FILE} {
    weekly
    rotate 12
    compress
    missingok
    notifempty
    su root root
    create 0640 root root
}
EOF
    log_success "${MSG_SUDO_LOGROTATE_DONE}"
}

# 校验 NOPASSWD 白名单：存在则 warn 提示风险
_check_nopasswd_risk() {
    local risk_found=0
    if [[ -f "${SUDOERS_MAIN}" ]] && grep -qE '^[^#]*NOPASSWD' "${SUDOERS_MAIN}" 2>/dev/null; then
        risk_found=1
    fi
    if [[ -d "${SUDOERS_DIR}" ]] && grep -qrE '^[^#]*NOPASSWD' "${SUDOERS_DIR}" 2>/dev/null; then
        risk_found=1
    fi
    if [[ ${risk_found} -eq 1 ]]; then
        log_warn "${MSG_SUDO_NOPASSWD_RISK}"
    fi
}

# ============================================================================
# 公共函数
# ============================================================================

# 应用 sudo 安全加固
apply_sudo_hardening() {
    log_title "${MSG_SUDO_TITLE}"

    _check_nopasswd_risk

    if ! _write_sudoers_dropin; then
        return 1
    fi

    _ensure_sudo_log_perms
    _write_logrotate_dropin

    log_success "${MSG_SUDO_DONE}"
    return 0
}

# ============================================================================
# sudo 加固向导
# ============================================================================

run_sudo_wizard() {
    log_title "${MSG_SUDO_WIZARD_TITLE}"

    echo ""
    echo -e "${BOLD}${MSG_SUDO_WIZARD_DESC}${NC}"
    echo ""

    if ! confirm "${MSG_SUDO_WIZARD_START}" "y"; then
        log_info "${MSG_SUDO_WIZARD_SKIPPED}"
        return 0
    fi

    local wizard_rc=0
    apply_sudo_hardening || wizard_rc=1

    if [[ ${wizard_rc} -eq 0 ]]; then
        log_success "${MSG_SUDO_WIZARD_DONE}"
    else
        log_warn "${MSG_SUDO_WIZARD_DONE} ${MSG_WIZARD_ERR_HINT}"
    fi

    return ${wizard_rc}
}

# 标记 sudo.sh 已加载
readonly _SUDO_LOADED=1

log_debug "sudo.sh loaded successfully"
